replicaCount: 1
image:
  repository: 060623762260.dkr.ecr.us-east-1.amazonaws.com/weather-api
  tag: c624a83
resources:
  requests:
    cpu: 100m        
    memory: 128Mi    
  limits:
    cpu: 250m       
    memory: 256Mi    
namespace: weather-api
ingress:
  host: weather.local
env:
  DB_SECRET_NAME: weather-api/db
  OPENWEATHER_SECRET_NAME: weather-api/openweather
  AWS_REGION: us-east-1
