apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-history-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aidaikin91/my-infra
    targetRevision: main
    path: helm/search-history
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: search-history

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
