apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  namespace: {{ .Values.namespace }}
  labels:
    app: weather-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      serviceAccountName: weather-api
      containers:
        - name: weather-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: DB_SECRET_NAME
              value: {{ .Values.env.DB_SECRET_NAME }}
            - name: OPENWEATHER_SECRET_NAME
              value: {{ .Values.env.OPENWEATHER_SECRET_NAME }}
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
