apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: weather-api
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
